### ISSUE TITLE
The Generalization ability to different video sequences

### ISSUE THREAD

**Issue by zhiyuanYU134** [Meowuu7/QuasiSim#4]
What a great job！But I want to know whether the model weights can generalize for different video sequences. And can 'Parameterized Quasi-Physical Simulator'  simulate multiple environments at the same time like issac gym?

**Comment by Meowuu7** [comment]
Hi @zhiyuanYU134 ,

Thank you for your interest. Since QuasiSim infers actions through per-trajectory optimization rather than training neural networks, the pre-trained weights are trajectory-specific and cannot generalize to different video sequences. Currently, the 'Parameterized Quasi-Physical Simulator' does not support multiple environments or parallel simulations. What sets it apart from mainstream simulators is its tunability, allowing for varying levels of optimizability and fidelity.

I hope this clarifies your questions. Thank you!

**Comment by zhiyuanYU134** [comment]
> Hi @zhiyuanYU134 ,
> 
> Thank you for your interest. Since QuasiSim infers actions through per-trajectory optimization rather than training neural networks, the pre-trained weights are trajectory-specific and cannot generalize to different video sequences. Currently, the 'Parameterized Quasi-Physical Simulator' does not support multiple environments or parallel simulations. What sets it apart from mainstream simulators is its tunability, allowing for varying levels of optimizability and fidelity.
> 
> I hope this clarifies your questions. Thank you!
Thanks for your immediate reply！Your answer is helpful for my question.

**Comment by zhiyuanYU134** [comment]
ｔｈａｎｋｓ　ｆｏｒ　ｙｏｕｒ　ｉｍｍｅｄｉａｔｅ　ｒｅｐｌｙ！ｙｏｕｒ　ａｎｓｗｅｒ　ｉｓ　ｈｅｌｐｆｕｌ．
